wad_admin/app/mod_wadconfig/controllers.py
# Import flask dependencies
from flask import Blueprint, request, render_template, \
     flash, session, redirect, url_for, Markup

try:
    from app.mod_auth.controllers import login_required
    from app.libs.shared import INIFILE, dbio_connect, Button
    from app.libs import HTML as simplehtml
    import wadservices_communicate as wad_com

except ImportError:
    from wad_admin.app.mod_auth.controllers import login_required
    from wad_admin.app.libs.shared import INIFILE, dbio_connect, Button
    from wad_admin.app.libs import HTML as simplehtml
    import wad_admin.wadservices_communicate as wad_com

dbio = dbio_connect() 

# logging
from werkzeug.local import LocalProxy
from flask import current_app
logger = LocalProxy(lambda: current_app.logger)

# Define the blueprint: 'auth', set its url prefix: app.url/auth
mod_blueprint = Blueprint('wadconfig', __name__, url_prefix='/wadadmin')

# Set the route and accepted methods
@mod_blueprint.route('/home/', methods=['GET', 'POST'])
@login_required
def home():
    """
    Just present a menu with choices; should all be require authorization
    """
    menus = [
    ]
    resourcesmenu=[
        { 'label':'server status', 'href':url_for('wadconfig.whatsup') }, #'whatsup'
        { 'label':'data sources', 'href':url_for('wadconfig_sources.default') },
        { 'label':'tags for selector rules', 'href':url_for('wadconfig_ruletags.default', gid=1) },
        { 'label':'WAD Processor', 'href':url_for('wadconfig_wadprocessor.default', gid=1) }, 
        { 'label':'WAD-QC database', 'href':url_for('wadconfig_dbtool.default') }, 
        { 'label':'User manager', 'href':url_for('auth_users.default') }, 
    ]

    configmenu=[
        { 'label':'factory modules', 'href':url_for('wadconfig_factorymodules.default', gid=1) }, 
        { 'label':'import modules', 'href':url_for('wadconfig_importexport.importing', gid=1) }, 
        { 'label':'export modules', 'href':url_for('wadconfig_importexport.exporting', gid=1) }, 
        { 'label':'backup selectors', 'href':url_for('wadconfig_backuprestore.backingup', gid=1) }, 
        { 'label':'restore selectors', 'href':url_for('wadconfig_backuprestore.restoring', gid=1) }, 
        { 'label':'selectors', 'href':url_for('wadconfig_selectors.default') }, 
    ]


    processmenu=[
        { 'label':'processes', 'href':url_for('wadconfig_processes.default') },
        { 'label':'results', 'href':url_for('wadconfig_results.default') }, 
    ]

    advancedmenu=[
        { 'label':'analysis modules', 'href':url_for('wadconfig_modules.default') },
        { 'label':'module configs',  'href':url_for('wadconfig_configs.default') }, 
        { 'label':'meta configs',  'href':url_for('wadconfig_metas.default') }, 
    ]

    menus.append({'title':'Resources', 'items':resourcesmenu})
    menus.append({'title':'Configuration', 'items':configmenu})
    menus.append({'title':'Processes/Results', 'items':processmenu})
    menus.append({'title':'Advanced', 'items':advancedmenu})
    return render_template("wadconfig/home.html", menus=menus, title='WAD-QC Server Administration')


@mod_blueprint.route('/whatsup/')
@login_required
def whatsup():
    # show the status of several services
    result = {}

    wp_start = Button('start', url_for('.wadcontrol', command='start'))
    wp_pause = Button('pause', url_for('.wadcontrol', command='pause'))
    wp_quit  = Button('quit', url_for('.wadcontrol', command='quit'))

    ort_start = Button('start', url_for('.orthanc', command='start'))
    ort_quit = Button('quit', url_for('.orthanc', command='quit'))

    psql_start = Button('start', url_for('.pgcontrol', command='start'))
    psql_reload = Button('reload', url_for('.pgcontrol', command='reload'))
    psql_quit = Button('quit', url_for('.pgcontrol', command='stop'))

    services = [ # process name, identifier on cmdline
                 {'name': 'postgresql', 'process':'postgresql', 'buttons':[psql_start, psql_reload, psql_quit]}, # at least for the Orthanc database
                 {'name': 'orthanc', 'process':'Orthanc', 'buttons':[ort_start, '', ort_quit]}, # preferred PACS solution 
                 {'name': 'wadprocessor', 'process':'wadprocessor', 'buttons':[wp_start, wp_pause, wp_quit]}, # wad_qc processor
                 ]    

    systemd_services = {'orthanc': 'wadorthanc', 'postgresql': 'wadpostgresql', 'wadprocessor': 'wadprocessor'}
    # set service status to NOT RUNNING
    for service in services:
        status = is_service_running(service['process'])
        if service['name'] in systemd_services.keys():
            systemd = wad_com.controlled_by_systemd(systemd_services[service['name']])
            if systemd:
                result["{} (controlled by systemd)".format(service['name'])] = {
                    'cell': simplehtml.TableCell(status[0], **status[1]) , 
                    'buttons':[]
                }
            else:
                result[service['name']] = {'cell': simplehtml.TableCell(status[0], **status[1]) , 'buttons':service['buttons']}

    table = simplehtml.Table(header_row=['Service',   'Status'])
    for service, status in sorted(result.items()):
        row = [service, status['cell']]
        row.extend(status['buttons'])
        table.rows.append(row)

    # versions
    hdr2 = "<H2>Versions</H2>"
    col_ok   = {'bgcolor':'yellowgreen'}
    col_bad =  {'bgcolor':'Red'}

    version_db   = dbio.DBVariables.get(dbio.DBVariables.name == 'iqc_db_version').val
    version_dbio = dbio.__version__
    import pkg_resources
    version_whl = pkg_resources.get_distribution("wad_qc").version
    
    table2 = simplehtml.Table(header_row=['Item',   'Version'])
    results2 = {}
    results2['WAD-QC DataBase'] = {'val': version_db, 'col': col_ok if version_db>=version_dbio else col_bad }
    results2['wad_qc.dbio'] = {'val': version_dbio, 'col': col_ok if version_dbio>=version_db else col_bad }
    results2['wad_qc whl'] = {'val': version_whl, 'col':{} }
    
    for service, vals in sorted(results2.items()):
        row = [service, simplehtml.TableCell(vals['val'], **vals['col'])]
        table2.rows.append(row)
    table2 = hdr2 + str(table2)

    table = str(table)+str(table2)

    return render_template("wadconfig/generic.html", title='Whatsup', html=Markup(table))

def is_service_running(service):
    # show the status of several services
    # service = cli identifier
    col =  {'bgcolor':'Red'}
    if service == 'wadprocessor':
        stat = wad_com.wadcontrol('status', INIFILE)
        if stat == 'ERROR':
            stat = 'stopped'
    elif service == 'postgresql':
        stat = wad_com.postgresql('status')
    else:
        stat = wad_com.status(service)

    if stat == 'paused': 
        col = {'bgcolor':'yellow'}
    elif stat == 'running': 
        col = {'bgcolor':'yellowgreen'}
    status = (stat, col)

    return status

@mod_blueprint.route('/wadcontrol/')
@login_required
def wadcontrol():
    _command = request.args['command'] if 'command' in request.args else None
    if not _command in ['start', 'quit', 'status', 'pause']:
        return redirect(url_for('.whatsup'))

    wad_com.wadcontrol(_command, INIFILE)
    return redirect(url_for('.whatsup'))

@mod_blueprint.route('/pgcontrol/')
@login_required
def pgcontrol():
    _command = request.args['command'] if 'command' in request.args else None
    if not _command in ['start', 'status', 'reload', 'stop']:
        return redirect(url_for('.whatsup'))

    wad_com.postgresql(_command)
    return redirect(url_for('.whatsup'))

@mod_blueprint.route('/orthanc/')
@login_required
def orthanc():
    _command = request.args['command'] if 'command' in request.args else None
    if not _command in ['start', 'quit']:
        return redirect(url_for('.whatsup'))

    if _command == 'start':
        wad_com.start('Orthanc', INIFILE)
    elif _command == 'quit':
        wad_com.stop('Orthanc')

    return redirect(url_for('.whatsup'))

wad_admin/app/templates/layout.html
{% from "macros.html" import nav_link with context %}
{% from "macros.html" import toggle_login_link with context %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WAD-QC Admin</title>
    <link href="{{ url_for('static', filename='bootstrap.min.css') }}" rel="stylesheet" media="screen">
    <link href="{{ url_for('static', filename='sticky-footer-navbar.css') }}" rel="stylesheet" media="screen">
    <link href="{{ url_for('static', filename='tablesorter/theme.wadred.css') }}" rel="stylesheet" media="screen">
    <link href="{{ url_for('static', filename='wad2.css') }}" rel="stylesheet" media="screen">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  <!-- Placed at the end of the document will make pages load faster, but also redraw table on slow machines -->
  <script src="{{ url_for('static', filename='jquery-1.12.4.min.js') }}"></script>
  <script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
  <script src="{{ url_for('static', filename='tablesorter/jquery.tablesorter.js') }}"></script>
  <script src="{{ url_for('static', filename='tablesorter/jquery.tablesorter.widgets.js') }}"></script>
  {% block refreshpage %}{% endblock %}
  <script>
  $(document).ready(function(){
    $("#sortTable").tablesorter({widgets:['zebra', 'filter']});
    $("#sortTableNoFilter").tablesorter({widgets:['zebra']});
    {% if add_refresh is defined %}
    checkReloading();
    {% endif %}
  });
  </script>
  </head>
  <body>
  <nav class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{{ url_for('wadconfig.home') }}">WAD-QC</a>
      </div>
  
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          {{ nav_link('wadconfig_selectors.default', 'Selectors') }}
          {{ nav_link('wadconfig_processes.default', 'Processes') }}
          {{ nav_link('wadconfig_results.default', 'Results') }}
          {{ nav_link('wadconfig_dbtool.default', 'DBTool') }}
        </ul>
        <ul class="nav navbar-nav">
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {{ toggle_login_link('auth.signin', 'Log in', 'auth.logout', 'Log out') }}
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>    
    <div class="container">
      <br>
      {% block content %}{% endblock %}
      <br>
    </div>
    {% block footer %} <!-- this is default footer -->
    <footer class="footer">
      <div class="container-fluid">
        <div id="poweredBy" class="pull-right">
          <img src="{{ url_for('static', filename='nvkf-logo-60-white.gif') }}" alt="NVKF" height="60" width="60"> <a href="https://www.nvkf.nl">NVKF</a>
        </div>
        <div class="pull-left">
          <br>
          Copyright © 2016
        </div>
      </div>
    </footer>
    {% endblock %}
  </body>
</html>

wad_admin/app/templates/macros.html
{% macro nav_link(endpoint, name) %}
{% if request.endpoint.endswith(endpoint) %}
    <li class="active"><a href="{{ url_for(endpoint) }}">{{name}}</a></li>
{% else %}
    <li><a href="{{ url_for(endpoint) }}">{{name}}</a></li>
{% endif %}
{% endmacro %}

{% macro toggle_login_link(endpoint_login, label_login, endpoint_logout, label_logout) %}
{% if session.get('logged_in') %}
    <li><a href="{{ url_for(endpoint_logout) }}">{{label_logout}}</a></li>
{% else %}
    <li><a href="{{ url_for(endpoint_login) }}">{{label_login}}</a></li>
{% endif %}
{% endmacro %}